/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TSTRING = 5;
  /** RegularExpression Id. */
  int TINTEIRO = 6;
  /** RegularExpression Id. */
  int TREAL = 7;
  /** RegularExpression Id. */
  int ARRAY = 8;
  /** RegularExpression Id. */
  int RECORD = 9;
  /** RegularExpression Id. */
  int IS = 10;
  /** RegularExpression Id. */
  int ENDRECORD = 11;
  /** RegularExpression Id. */
  int OF = 12;
  /** RegularExpression Id. */
  int OFRECORD = 13;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 14;
  /** RegularExpression Id. */
  int STRING = 15;
  /** RegularExpression Id. */
  int INTEIRO = 16;
  /** RegularExpression Id. */
  int REAL = 17;
  /** RegularExpression Id. */
  int LETRA = 18;
  /** RegularExpression Id. */
  int DIGITO = 19;
  /** RegularExpression Id. */
  int DOISPONTOS = 20;
  /** RegularExpression Id. */
  int PONTOEVIRGULA = 21;
  /** RegularExpression Id. */
  int INTERVALO = 22;
  /** RegularExpression Id. */
  int VIRGULA = 23;
  /** RegularExpression Id. */
  int PARENTESQ = 24;
  /** RegularExpression Id. */
  int PARENTEDIR = 25;
  /** RegularExpression Id. */
  int ASPAS = 26;
  /** RegularExpression Id. */
  int PONTO = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"string\"",
    "\"integer\"",
    "\"real\"",
    "\"array\"",
    "\"record\"",
    "\"is\"",
    "\"endrecord\"",
    "\"of\"",
    "\"of record\"",
    "<IDENTIFICADOR>",
    "<STRING>",
    "<INTEIRO>",
    "<REAL>",
    "<LETRA>",
    "<DIGITO>",
    "\":\"",
    "\";\"",
    "\"..\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
    "\".\"",
  };

}
